version: 0.0.1
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: zYh2E1Ev8iysKYqh1JQnjA==
  DOCKER_PASS:
    secure: fzKLKWlgyXg+GYPF9tvvrA==

install:
  docker version

build_script:
  docker build -t solthoth/dotnetnuke:latest .

deploy_script:
  docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  docker push solthoth/dotnetnuke

notifications:
  provider: Slack
  auth_token:
    secure: AhTszfCytEwnM/zYyS6R1CU4ZtwMMR6HT4dcu9ArXziM1Z50SD5wDx/HoutzECX/v+6RP4HRHMc7VHw1sKXqL4IYq9j7lcuzw4AgyCcdNZs=
  channel: '#continues-integration'