version: 0.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: zYh2E1Ev8iysKYqh1JQnjA==
  DOCKER_PASS:
    secure: fzKLKWlgyXg+GYPF9tvvrA==

install:
  docker version
build_script:
  - docker build -t solthoth/dotnetnuke:latest .
  - ps: docker tag solthoth:dotnetnuke:latest solthoth/dotnetnuke:"$env:APPVEYOR_BUILD_VERSION"
before_deploy:
  ps: docker login -u "$env:DOCKER_USER" -p "$env:DOCKER_PASS"
deploy_script:
  - docker push solthoth/dotnetnuke:latest
  - docker push solthoth/dotnetnuke:"$env:APPVEYOR_BUILD_VERSION"
after_deploy:
  docker logout

notifications:
  provider: Slack
  auth_token:
    secure: AhTszfCytEwnM/zYyS6R1CU4ZtwMMR6HT4dcu9ArXziM1Z50SD5wDx/HoutzECX/v+6RP4HRHMc7VHw1sKXqL4IYq9j7lcuzw4AgyCcdNZs=
  channel: '#continues-integration'